apiVersion: v1
kind: ConfigMap
apiVersion: v1
metadata:
  name: etcd3-onramp-hawkular-agent
data:
  hawkular-openshift-agent: |
    endpoints:
    - type: prometheus
      protocol: "https"
      port: 9779
      path: /metrics
      collection_interval_secs: 5
      metrics:
      - name: etcd_server_has_leader
        type: gauge
      - name: etcd_server_leader_changes_seen_total
        type: counter
      - name: etcd_server_proposals_committed_total
        type: gauge
      - name: etcd_server_proposals_applied_total
        type: gauge
      - name: etcd_server_proposals_pending
        type: gauge
      - name: etcd_server_proposals_failed_total
        type: counter
